"""add_verification_fields

Revision ID: ef0698c7e761
Revises: ee326e3e2d55
Create Date: 2026-03-16 13:23:25.115644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef0698c7e761'
down_revision: Union[str, None] = 'ee326e3e2d55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_alerts', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('animals', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('farmers', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('verification_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verification_token')
    op.drop_column('users', 'is_verified')
    op.drop_column('farmers', 'created_at')
    op.drop_column('animals', 'created_at')
    op.drop_column('ai_alerts', 'created_at')
    # ### end Alembic commands ###
