"""Add device usage table

Revision ID: 0f2d5083ce3f
Revises: ef0698c7e761
Create Date: 2026-03-17 14:37:52.992172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f2d5083ce3f'
down_revision: Union[str, None] = 'ef0698c7e761'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_usages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('device_hash', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('daily_message_count', sa.Integer(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_usages_device_hash'), 'device_usages', ['device_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_usages_device_hash'), table_name='device_usages')
    op.drop_table('device_usages')
    # ### end Alembic commands ###
