"""Fix add daily message tracking

Revision ID: 484bed19f18e
Revises: 6b978d087538
Create Date: 2026-03-10 04:49:41.029945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '484bed19f18e'
down_revision: Union[str, None] = '6b978d087538'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('daily_message_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_message_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_message_at')
    op.drop_column('users', 'daily_message_count')
    # ### end Alembic commands ###
