"""Add doctor applications and emergency logs

Revision ID: 64bde8daaf88
Revises: 484bed19f18e
Create Date: 2026-03-10 14:01:23.263183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64bde8daaf88'
down_revision: Union[str, None] = '484bed19f18e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_applications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('qualification', sa.String(), nullable=False),
    sa.Column('specialization', sa.String(), nullable=False),
    sa.Column('experience_years', sa.Integer(), nullable=False),
    sa.Column('district', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emergency_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('users', 'credits_remaining',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'daily_message_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'has_subscription',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'has_subscription',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'daily_message_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'credits_remaining',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('emergency_logs')
    op.drop_table('doctor_applications')
    # ### end Alembic commands ###
