"""add_legacy_farm_management_tables

Revision ID: ee326e3e2d55
Revises: 64bde8daaf88
Create Date: 2026-03-10 16:02:42.476778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee326e3e2d55'
down_revision: Union[str, None] = '64bde8daaf88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('alert_id', sa.String(), nullable=False),
    sa.Column('farm', sa.String(), nullable=False),
    sa.Column('tag_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('time_label', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_alerts_alert_id'), 'ai_alerts', ['alert_id'], unique=True)
    op.create_table('farmers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('contact', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farmers_name'), 'farmers', ['name'], unique=False)
    op.create_table('animals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tag_id', sa.String(), nullable=False),
    sa.Column('species', sa.String(), nullable=False),
    sa.Column('breed', sa.String(), nullable=False),
    sa.Column('health_status', sa.String(), nullable=False),
    sa.Column('recent_diagnosis', sa.String(), nullable=True),
    sa.Column('farmer_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_animals_tag_id'), 'animals', ['tag_id'], unique=True)
    op.create_table('farm_consultations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ticket_id', sa.String(), nullable=False),
    sa.Column('animal_id', sa.String(), nullable=False),
    sa.Column('farmer_id', sa.String(), nullable=False),
    sa.Column('symptom', sa.String(), nullable=False),
    sa.Column('diagnosis', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farm_consultations_ticket_id'), 'farm_consultations', ['ticket_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_farm_consultations_ticket_id'), table_name='farm_consultations')
    op.drop_table('farm_consultations')
    op.drop_index(op.f('ix_animals_tag_id'), table_name='animals')
    op.drop_table('animals')
    op.drop_index(op.f('ix_farmers_name'), table_name='farmers')
    op.drop_table('farmers')
    op.drop_index(op.f('ix_ai_alerts_alert_id'), table_name='ai_alerts')
    op.drop_table('ai_alerts')
    # ### end Alembic commands ###
